-- MySQL Script generated by MySQL Workbench
-- 11/23/14 22:45:13
-- Model: New Model    Version: 1.0

-- -----------------------------------------------------
-- Schema SGI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGI` DEFAULT CHARACTER SET utf8 ;
USE `SGI` ;

-- -----------------------------------------------------
-- Table `SGI`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGI`.`almacen` (
  `id_alm` INT NOT NULL AUTO_INCREMENT,
  `nombre_alm` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_alm`),
  UNIQUE INDEX `nombre_alm_UNIQUE` (`nombre_alm` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGI`.`movimiento` (
  `id_mov` INT NOT NULL AUTO_INCREMENT,
  `tipo_mov` INT NOT NULL,
  `almacen_id_alm` INT NOT NULL,
  `fecha_det_mov` DATE NOT NULL,
  PRIMARY KEY (`id_mov`, `almacen_id_alm`),
  INDEX `fk_movimiento_almacen1_idx` (`almacen_id_alm` ASC),
  CONSTRAINT `fk_movimiento_almacen1`
    FOREIGN KEY (`almacen_id_alm`)
    REFERENCES `SGI`.`almacen` (`id_alm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGI`.`area` (
  `id_are` INT NOT NULL AUTO_INCREMENT,
  `nombre_are` VARCHAR(100) NULL,
  PRIMARY KEY (`id_are`),
  UNIQUE INDEX `nombre_are_UNIQUE` (`nombre_are` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGI`.`usuario` (
  `id_usu` INT NOT NULL AUTO_INCREMENT,
  `nombre_usu` VARCHAR(32) NULL,
  `clave_usu` VARCHAR(32) NULL,
  `permisos_usu` INT NULL,
  `almacen_id_alm` INT NULL,
  `area_id_are` INT NULL,
  PRIMARY KEY (`id_usu`),
  UNIQUE INDEX `usuario_usu_UNIQUE` (`nombre_usu` ASC),
  INDEX `fk_usuario_almacen1_idx` (`almacen_id_alm` ASC),
  INDEX `fk_usuario_Area1_idx` (`area_id_are` ASC),
  CONSTRAINT `fk_usuario_almacen1`
    FOREIGN KEY (`almacen_id_alm`)
    REFERENCES `SGI`.`almacen` (`id_alm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_Area1`
    FOREIGN KEY (`area_id_are`)
    REFERENCES `SGI`.`area` (`id_are`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGI`.`pedido` (
  `id_ped` INT NOT NULL AUTO_INCREMENT,
  `Area_id_are` INT NOT NULL,
  `fecha_ped` DATE NOT NULL,
  `id_usu_ped` INT NOT NULL,
  PRIMARY KEY (`id_ped`, `Area_id_are`),
  INDEX `fk_Pedido_Area1_idx` (`Area_id_are` ASC),
  INDEX `fk_pedido_usuario1_idx` (`id_usu_ped` ASC),
  CONSTRAINT `fk_Pedido_Area1`
    FOREIGN KEY (`Area_id_are`)
    REFERENCES `SGI`.`area` (`id_are`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`id_usu_ped`)
    REFERENCES `SGI`.`usuario` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`TipoArticulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGI`.`TipoArticulo` (
  `idTipoArticulo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tip` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTipoArticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGI`.`articulo` (
  `id_art` INT NOT NULL AUTO_INCREMENT,
  `nombre_art` VARCHAR(200) NOT NULL,
  `unidad_art` VARCHAR(45) NOT NULL,
  `cantidad_art` INT NOT NULL,
  `TipoArticulo_id_tip_art` INT NOT NULL,
  `codigo_art` VARCHAR(30) NULL,
  PRIMARY KEY (`id_art`),
  INDEX `fk_articulo_TipoArticulo1_idx` (`TipoArticulo_id_tip_art` ASC),
  CONSTRAINT `fk_articulo_TipoArticulo1`
    FOREIGN KEY (`TipoArticulo_id_tip_art`)
    REFERENCES `SGI`.`TipoArticulo` (`idTipoArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`detalle_movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGI`.`detalle_movimiento` (
  `id_det_mov` INT NOT NULL AUTO_INCREMENT,
  `movimiento_id_mov` INT NOT NULL,
  `articulo_id_art` INT NOT NULL,
  `cantidad_det_mov` INT NOT NULL,
  PRIMARY KEY (`id_det_mov`, `movimiento_id_mov`),
  INDEX `fk_detalle_movimiento_Movimiento1_idx` (`movimiento_id_mov` ASC),
  INDEX `fk_detalle_movimiento_articulo1_idx` (`articulo_id_art` ASC, `cantidad_det_mov` ASC),
  CONSTRAINT `fk_detalle_movimiento_Movimiento1`
    FOREIGN KEY (`movimiento_id_mov`)
    REFERENCES `SGI`.`movimiento` (`id_mov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_movimiento_articulo1`
    FOREIGN KEY (`articulo_id_art`)
    REFERENCES `SGI`.`articulo` (`id_art`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGI`.`detalle_pedido` (
  `id_det_ped` INT NOT NULL AUTO_INCREMENT,
  `Pedido_id_ped` INT NOT NULL,
  `articulo_id_art` INT NOT NULL,
  `cantidad_art` INT NULL,
  PRIMARY KEY (`id_det_ped`, `Pedido_id_ped`),
  INDEX `fk_detalle_pedido_Pedido1_idx` (`Pedido_id_ped` ASC),
  INDEX `fk_detalle_pedido_articulo1_idx` (`articulo_id_art` ASC),
  CONSTRAINT `fk_detalle_pedido_Pedido1`
    FOREIGN KEY (`Pedido_id_ped`)
    REFERENCES `SGI`.`pedido` (`id_ped`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_pedido_articulo1`
    FOREIGN KEY (`articulo_id_art`)
    REFERENCES `SGI`.`articulo` (`id_art`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGI`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGI`.`registro` (
  `id_reg` INT NOT NULL AUTO_INCREMENT,
  `id_usu_reg` INT NOT NULL,
  `fecha_reg` DATE NOT NULL,
  `hora_reg` TIME NULL,
  PRIMARY KEY (`id_reg`),
  INDEX `fk_Registro_usuario1_idx` (`id_usu_reg` ASC),
  CONSTRAINT `fk_Registro_usuario1`
    FOREIGN KEY (`id_usu_reg`)
    REFERENCES `SGI`.`usuario` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

